#pragma once
// =============================================================================
// order.h  —  Stage 1 & 3: Cache-Aligned Order Structure
// =============================================================================
//
// CONCEPT: Cache Line Alignment
// A modern CPU cache line is 64 bytes. When the CPU fetches memory it always
// loads an entire 64-byte cache line. If an Order struct crosses two cache
// lines, every access costs TWO cache misses instead of one.
//
// By aligning Order to 64 bytes and sizing it to exactly 64 bytes we get:
//   • One cache miss per Order access (best case)
//   • No false sharing between adjacent Orders in an array
//   • Predictable memory layout for SIMD / prefetch instructions
//
// In HFT this matters because the order hot path runs millions of times per
// second. Saving even 50 ns per order can add up to real P&L.
// =============================================================================

#include <cstdint>
#include <cstring>
#include <chrono>

// ---------------------------------------------------------------------------
// Side: whether this order is a buy or a sell
// ---------------------------------------------------------------------------
enum class Side : uint8_t {
    Buy  = 0,
    Sell = 1
};

// ---------------------------------------------------------------------------
// OrderStatus: lifecycle state of an order
// ---------------------------------------------------------------------------
enum class OrderStatus : uint8_t {
    Pending  = 0,   // just generated by feed
    Accepted = 1,   // passed risk checks
    Rejected = 2    // failed risk checks
};

// ---------------------------------------------------------------------------
// Order — the central data structure of the whole engine
//
// alignas(64) forces the struct to start on a 64-byte boundary.
// The explicit padding field ensures the struct is EXACTLY 64 bytes so that
// when packed into an array, each element occupies exactly one cache line.
//
// Field layout (total = 64 bytes):
//   order_id       8 B  — unique monotonic ID
//   timestamp_ns   8 B  — nanosecond timestamp when feed generated this order
//   price          8 B  — limit price (double for speed; use fixed-point in prod)
//   quantity       8 B  — number of shares / contracts
//   symbol_hash    8 B  — pre-hashed symbol ID (avoids string comparison on hot path)
//   ingress_ns     8 B  — timestamp when order entered the ring buffer
//   side           1 B  — Buy or Sell
//   status         1 B  — Pending / Accepted / Rejected
//   symbol[6]      6 B  — human-readable symbol (for logging only)
//   _pad[8]        8 B  — explicit padding to reach exactly 64 bytes
// ---------------------------------------------------------------------------
struct alignas(64) Order {
    uint64_t    order_id;       // 8 B
    uint64_t    timestamp_ns;   // 8 B  — time of creation at the feed
    double      price;          // 8 B
    double      quantity;       // 8 B
    uint64_t    symbol_hash;    // 8 B
    uint64_t    ingress_ns;     // 8 B  — time of ring-buffer insertion (latency start)
    Side        side;           // 1 B
    OrderStatus status;         // 1 B
    char        symbol[6];      // 6 B  — e.g. "AAPL\0"
    uint8_t     _pad[8];        // 8 B  — explicit padding
};

// Compile-time guarantee: struct must be exactly one cache line.
// Placed outside the struct to avoid the "incomplete type" pitfall.
// If this fires you've added or removed fields without adjusting _pad.
static_assert(sizeof(Order) == 64, "Order must be exactly 64 bytes (one cache line)");
static_assert(alignof(Order) == 64, "Order must be 64-byte aligned");

// ---------------------------------------------------------------------------
// Helper: fill an Order with zero / default values
// Faster than a constructor for POD-style reset in a pool allocator.
// ---------------------------------------------------------------------------
inline void reset_order(Order& o) noexcept {
    // std::memset is a single optimised memset on most platforms
    std::memset(&o, 0, sizeof(Order));
}

// ---------------------------------------------------------------------------
// Helper: current wall-clock time in nanoseconds
// Used to stamp orders on the feed thread and again on the consumer thread.
// ---------------------------------------------------------------------------
[[nodiscard]] inline uint64_t now_ns() noexcept {
    return static_cast<uint64_t>(
        std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::high_resolution_clock::now().time_since_epoch()
        ).count()
    );
}
